### ISSUE TITLE
SwitchToWindow error at SeleniumVBA.xlam （v5.3）

### ISSUE THREAD

**Issue by camel47** [GCuser99/SeleniumVBA#106]
When I used the SeleniumVBA add-in SeleniumVBA.xlam v3.7, the SwitchToWindow command worked without any problems, but after upgrading to SeleniumVBA.xlam v5.3, the SwitchToWindow command gave me a compile error "Method or data member not found." I tried driver.SwitchToWindow and driver.SwitchToNextWindow, but in v5.3, both gave me compile errors. I'm sorry for being a beginner, but I would appreciate it if you could tell me the solution. Thank you in advance.

**Comment by 6DiegoDiego9** [comment]
Hi @camel47, search "SwitchToWindow" in this page to see the new solution: https://github.com/GCuser99/SeleniumVBA/discussions/86#discussioncomment-6824675

**Comment by camel47** [comment]
Thank you for your help!

I really appreciate it.

2024年7月4日(木) 19:19 Diego ***@***.***>:
