### ISSUE TITLE
runtime error CreateCapabilities must be invoked after the StartEdge or StartChromeMethods, and before OpenBrowser Methods

### ISSUE THREAD

**Issue by dornech** [GCuser99/SeleniumVBA#120]
I use the DLL and get the abovementioned error:
![image](https://github.com/user-attachments/assets/cc91ade9-e1db-486d-9966-beed8dbde24b)

The error occurs whenever I start a VBA routine second time. All objects are properly ended (CloseBrowser / Shutdown) and object references are set to nothing (what should happen when a program ends anyway). Also the chromedriver.exe process is not active anymore.

It seems the DLL lacks some internal clean up ?

**Comment by dornech** [comment]
Check for a difference between DLL and addin - error occurs for addin version as well what I would not have expected.

**Comment by GCuser99** [comment]
I can't replicate on my end (Windows 11, Excel 365 64-bit). Can you provide more info about your system and some reproducible code?

On your system, I thought you said you were using Office 2003 - is that true?

**Comment by dornech** [comment]
Yes, using Office2003.
I did some additional testing - I use a own initialisation routine to allow to set some stuff lieke stealthening (i e something I could achieve with application specific ini file). I think I execute the commands in the appropriate order.

**Comment by dornech** [comment]
I reconsidered - I think it was a strange error in my code. I used a static var to track the status and I thought this would be deleted/reset after the run which is obvoiously not the case. but with the status-checker s(see other thread) I could make it work the way I want it to

**Comment by dornech** [comment]
Own error
