### ISSUE TITLE
strange issue with ScrollIntoView

### ISSUE THREAD

**Issue by dornech** [GCuser99/SeleniumVBA#126]
Lets assume I have a Webelement down the page I want to scroll to.
For testing/debugging I reference the VBA add-in noth the DLL.
In real code  I use findelement for this without object assignment but I omit this here to make it more clear because I think that should not not make the difference here, should it?

objWebElt.ScrollIntoView
-> does not work during regular execution, does only scroll by a few lines horizontally
-> does work in debug mode (stepping with F8)

objWebDriver.ExecuteScript "arguments[0].scrollIntoView({behavior: ""auto"", block: ""start"", inline: ""nearest""})", objWebElt
-> does work (regular execution & debugging/F8-stepping

objWebDriver.ExecuteScript "arguments[0].scrollIntoView()", objWebElt
-> does work (regular execution & debugging/F8-stepping

Strange, isn't it?

**Comment by dornech** [comment]
I did some research and some developers embbed the scrollintoview into a one-time timeout with setTimeout(callback, x) with x being in one example 0, in the other 50. Might be an idea in general, I already discovered that scrolling takes some time (execution seems not to be 100% syncronously i e executescript coming back after scroll is done and so this might help to avoid waits.
But unfortunately the current issue seems not to be resolved.

**Comment by GCuser99** [comment]
@dornech, I'm "driving blind" in trying to debug this issue without a reproducible use-case. Can you help me out? Otherwise it may take a while to construct one on my own. Will get back to you as soon as I can...

**Comment by dornech** [comment]
Unfortunately the problem occurs in a protected area with sensitive data, I tried my very best to explain it as generally as possible. 

I can overcome the problem in my case with a movetoelement action chain. This might be an option for others as well.

**Comment by GCuser99** [comment]
@dornech, does the following work on your system?
```vba
objWebElt.ScrollIntoView enSpeed:=jump_instant
```

**Comment by GCuser99** [comment]
I've concluded that this thread belongs in Discussions - this is an intrinsic problem with jscript's scrollIntoView when using smooth scrolling...
