### ISSUE TITLE
How to print two dimensional array using TableToArray() ?

### ISSUE THREAD

**Issue by yycc97** [GCuser99/SeleniumVBA#127]
Hi, I'm using the function of TableToArray(), but it can only return 1 even if there are multiple columns in a table of a webpage.
For example, there are 11 colums as below:
![スクリーンショット 2024-10-22 140320](https://github.com/user-attachments/assets/52cdd2e2-2706-4c89-b123-d035c1032de7)

the VBA code
  
  ``` 
   table = driver.FindElement(By.ID, "TheTable").TableToArray()

   For i = 1 To UBound(table, 2)

   If Not IsEmpty(table) Then
    Debug.Print UBound(table, 2)

    Else
    Debug.Print ""

    End If     
   
 Next i 
```
But it can only find one column.
![image](https://github.com/user-attachments/assets/fa7d592f-38bc-40fa-8acb-8947902c52e3)

Am I using TableToArray() correctly ?
Thanks for your help.

**Comment by dornech** [comment]
Well, beside the fact it's more a discussion than an issue: I think your access to the table is wrong. You need to loops - one per dimension. 

```
For row = 1 To UBound(table, 1)
   For column = 1 to UBound(table, 2)
      debug.print table(row, column)
   Next
Next
```

**Comment by GCuser99** [comment]
@yycc97 did that work for you or are you still only getting one column?

**Comment by yycc97** [comment]
@GCuser99 @dornech Sorry for my late reply ! 
After trying the above code, I'm not getting one column, but the strange thing is that there's no any output for rows and columns.
```
table = driver.FindElement(By.ID, "TheTable").TableToArray(skipHeader:=True)
    
    Debug.Print "Running the loop!"
    
     For row = 1 To UBound(table, 1)
       For column = 1 To UBound(table, 2)
          Debug.Print table(row, column)
       Next
     Next
``` 
![image](https://github.com/user-attachments/assets/d31b8d2c-080e-4b26-8fe7-893145a2a025)

Also, for the code as below, it can still print out all the rows but only one column. 
![image](https://github.com/user-attachments/assets/d8820722-63e6-4f04-91c7-b98efaacabd9)
![image](https://github.com/user-attachments/assets/2ce52bbe-16c4-4e4d-bc2f-5cc7b2d3d697)

Thanks for your quick response as always !

**Comment by GCuser99** [comment]
What do you get for the size of table array?
```vba
Debug.Print UBound(table, 1), UBound(table, 2)
```

**Comment by yycc97** [comment]
I get like this ↓
![image](https://github.com/user-attachments/assets/2afc9764-77b9-4ce6-a711-58fe772d6381)

**Comment by GCuser99** [comment]
That is interesting. The image in your original post showed 1x11 table - this one is 8x1. So I wonder if there are more than one element with ID = "TheTable" in your document? Let's see:

```vba
Debug.Print driver.FindElements(By.ID, "TheTable").Count
```
If that prints more than "1", then you might have to use an XPath locator instead of ID to get the correct table.

**Comment by dornech** [comment]
The yellow marked looks wrong to my eyes. You should use the dimension index with the array variant variable but not an element.

**Comment by dornech** [comment]
Ah, and by the way: I started with index 1 assuming you use Option Base 1. However, standard is 0

**Comment by yycc97** [comment]
> That is interesting. The image in your original post showed 1x11 table - this one is 8x1. So I wonder if there are more than one element with ID = "TheTable" in your document? Let's see:
> 
> ```vba
> Debug.Print driver.FindElements(By.ID, "TheTable").Count
> ```
> 
> If that prints more than "1", then you might have to use an XPath locator instead of ID to get the correct table.

Yes ! It prints out 2 ! Actually the table in my document has a dynamic number of rows and a fixed number of columns (always 11).
![2](https://github.com/user-attachments/assets/bb173ee2-ca84-4ae7-92f2-641859987c6a) 
It's hard to notice 🥹

And with an XPath locator the code works well !
```
   For row = 1 To UBound(table, 1)
     For column = 1 To UBound(table, 2)
      Debug.Print table(row, column)
    Next
   Next
```
Thank you @GCuser99 @dornech very much !!
