### ISSUE TITLE
WebElements Class?

### ISSUE THREAD

**Issue by GCuser99** [GCuser99/SeleniumVBA#5]
Would make it easier to work with the result of FindElements method. Currently have to stuff into an array of type WebElement:
```
Dim elements() as WebElement
elements = driver.FindElementsByID ("searchid")
Debug.Print "num elements found: " & ubound(elements)+1
```
but this might be better:
```
Dim elements as WebElements
set elements = driver.FindElementsByID ("searchid")
Debug.Print "num elements found: " & elements.Count
```

**Comment by interservices** [comment]
Not only this.  Also, looping with a "for each" is convenient over looping with an i(ndex) and ubound(s).

**Comment by GCuser99** [comment]
Yep - I added the needed Attribute lines in the class so that For Each is enabled, as well as making Item method the default method so that:
```
Dim elements as WebElements
set elements = driver.FindElementsByID ("searchid")
Debug.Print "3rd Element Text: " & elements(3).GetText
```
