### ISSUE TITLE
About the new "Trust Access to VBA ..." requirement

### ISSUE THREAD

**Issue by 6DiegoDiego9** [GCuser99/SeleniumVBA#68]
Some days ago, I updated the SeleniumVBA library in a file with a simple web automation macro which is used by a couple of colleagues.

Unfortunately, my colleagues contacted me because they got stuck this error of the new ActiveVBAProjectFolderPath() function:
 ```
If Not VBAIsTrusted Then
    Err.raise 1, "WebShared", "Error: No Access to VB Project" & vbNewLine & vbNewLine & "File > Options > Trust Center > Trust Center Settings > Macro Settings > Trust Access to VBA project object model"
End If
    
On Error Resume Next
    strPath = Application.VBE.ActiveVBProject.FileName
On Error GoTo 0
```
I quickly semi-fixed that by adding a procedure, that I already made for other purposes and had in my master library, which enables the "Trust Access to VBA project object model" (semi-)automatically.  See my [pull request](https://github.com/GCuser99/SeleniumVBA/pull/66).

However, I think that requesting users to loosen Excel security permissions is conceptually too much as general requirement for SeleniumVBA, even if it were practically fully automated.  Is that now really unavoidable?

**Comment by GCuser99** [comment]
@6DiegoDiego9, very cool - I like it!

I tested it on three different Windows/Office version combinations, and it worked except for one edge issue. On my systems, if I canceled out of the msgbox, the Excel trust settings checkbox gets out-of-sync with VBAIsTrusted return value. It got confusing. So what do you think about this version of your code? I removed the Excel dialog loop and then restore the registry state to original if user hit cancel during the interaction. Tested on my systems and worked as expected. Anyway, good work on this!

```vba
Public Sub Enforce_Trust_Access_to_VBA_Project_Object_Model(Optional ByVal val As Boolean = True)
'in case it's not already enabled, programmatically (assist the user to) enable-enforce the "Trust Access to VBA ..." option
    Dim valTrustSetting As Long
    Dim modifiedHKLMTrustSetting As Boolean
    Dim pathHKLM As String
    Dim saveHKLMTrustSetting As Long
    Dim modifiedHKCUTrustSetting As Boolean
    Dim pathHKCU As String
    Dim saveHKCUTrustSetting As Long
    Dim res As Long
    
    If Not VBAIsTrusted Then
        Dim SHost As Object
        
        If val Then valTrustSetting = 1 Else valTrustSetting = 0

        On Error GoTo UserIntv
        Set SHost = CreateObject("WScript.Shell")
        
        modifiedHKLMTrustSetting = False
        On Error Resume Next
        'First, check if the HKLocalMachine key for Office app security is present
        pathHKLM = "HKLM\SOFTWARE\Microsoft\Office\" + Trim(Application.Version) + "\" & Replace(Trim(Application.Name), "Microsoft ", "") & "\Security\AccessVBOM"
        saveHKLMTrustSetting = SHost.RegRead(pathHKLM)
        If Err.Number = 0 Then 'If the key is present then enable/disable access to the VBA Project
            'save the setting in case user changes mind in later
            If saveHKLMTrustSetting <> valTrustSetting Then
                SHost.RegWrite pathHKLM, valTrustSetting, "REG_DWORD"
                modifiedHKLMTrustSetting = True
            End If
        End If
        Err.Clear

        On Error GoTo UserIntv
        'Second, overwrite the HKCurrentUser key to enable/disable access to the VBA Project
        modifiedHKCUTrustSetting = False
        pathHKCU = "HKCU\SOFTWARE\Microsoft\Office\" + Trim(Application.Version) + "\" & Replace(Trim(Application.Name), "Microsoft ", "") & "\Security\AccessVBOM"
        'save the setting in case user changes mind in later
        saveHKCUTrustSetting = SHost.RegRead(pathHKCU)
        If saveHKCUTrustSetting <> valTrustSetting Then
            SHost.RegWrite pathHKCU, valTrustSetting, "REG_DWORD"
            modifiedHKCUTrustSetting = True
        End If
        On Error GoTo 0
        
        'instruct/prepare user for what's comming next...
        res = MsgBox("Press ""OK"" in the following Macro Settings dialog window" & vbNewLine & "to enable the ""Trust Access to VBA Project Object Model"" setting", vbOKCancel)
        If res = vbOK Then
            'here it comes...
            Application.CommandBars.ExecuteMso ("MacroSecurity")
        End If
        
        If Not VBAIsTrusted Then
            'then user had second thoughts, canceled and decided to give Diego a call first :-)
            'so put things back the way they were...
            On Error Resume Next
            If modifiedHKLMTrustSetting Then
                SHost.RegWrite pathHKLM, saveHKLMTrustSetting, "REG_DWORD"
            End If
            If modifiedHKCUTrustSetting Then
                SHost.RegWrite pathHKCU, saveHKCUTrustSetting, "REG_DWORD"
            End If
            On Error GoTo 0
            GoTo UserIntv
        End If
            
    End If
    Exit Sub
UserIntv:
Err.Raise 1, , "Please Enable ""Trust Access to VBA Project Object Model"" in ""File > Options > Trust Center > Trust Center Settings > Macro Settings > Trust Access to VBA project object model"""
End Sub
```

**Comment by GCuser99** [comment]
BTW @6DiegoDiego9, the Trust Access to VBA is not a new requirement - the requirement has been there for quite some time. When I recently installed SeleniumVBA to a relatively new pc, which happened to have Excel's Trust Access to VBA setting unchecked, Application.VBE.ActiveVBProject.Filename errored because of the trust setting. Adding the VBAIsTrusted check was my (less elegant than yours) attempt to warn/instruct the user. So I think your clients would have still run into a problem either way (?). 

As far as whether we need trusted access to VBA project at all... it's a good question...

The only function that it serves now is to help set the default base folder path for calculating relative paths. Currently the base folder path is the active code project's host document folder path which requires access to VBA project to determine. I'm open to discussing other options for that. It started out being fso.GetFolderName(ThisWorkbook.path) but when we switched to the Add-in model, I realized that (at least in my usage), using the add-in's folder location was not ideal - it made more sense to me to use the caller's folder location. 

The options for default base folder path that I can think of:
1) folder location of the active code project's host document (currently used but requires trust to VBA project)
2) folder location of the SeleniumVBA add-in (this was the old way and not my favorite, but I could live with it)
3) CurDir() at the time of object initialization (easy to implement but could cause some confusion - mine is USAULLY set to the documents folder)
4) Expect user to first provide a base path through DefaultIOFolder method if he/she is using relative paths - only throw an error if user specifies a relative path without first setting the base path (I can live with this one - its more work for user but unlike the others above, leaves no ambiguity)

On method 4 - it might work like this:
```vba
'the following 3 lines would work without error
driver.DefaultIOFolder = ThisWorkbook.path
driver.SaveStringToFile htmlStr, ".\snippet.html"
driver.NavigateToFile ".\snippet.html"
```
```vba
'but SaveStringToFile method in this case would throw an error like:
'When specifying a relative path, please first use the DefaultIOFolder method to set the base folder path needed for resolving the intended full path."
'driver.DefaultIOFolder = ThisWorkbook.path '<- user forgets to specify base folder path
driver.SaveStringToFile htmlStr, ".\snippet.html"
driver.NavigateToFile ".\snippet.html"
```
I could live with any of those options (although my least favorite is option 2), and I am open to other ideas. I agree with you that requesting the user to lower the security permissions is not ideal, and maybe should be avoided.

**Comment by 6DiegoDiego9** [comment]
Out of sync/confusing Trust ... setting: 100% agree with you and your solution! thanks for the fix :)

About your 4 options, I'm OK with 1, I'm more thinking about to limit its use to the unavoidable cases: for example, If I run a simple script with no .INI use nor specified relative paths, is checking the active project path still useful for something?

**Comment by GCuser99** [comment]
On the base path options, is it that you are indifferent, or that you prefer option 1 (the current way)? Because your comments above about lowering permissions have got me leaning away from option 1. If you are indifferent, then I will start testing the other options for a safer way...

Anyway, while we digest this issue further, I think I can make one small change to WebDriver's initialization routine so that the ActiveVBAProjectFolderPath procedure only gets called when/if needed. Also, I have confirmed that it is only needed when user has not specified a base path for a relative path calculation - after the small fix it would not get called for processing the optional ini file settings.

Thanks!

**Comment by 6DiegoDiego9** [comment]
My fav. is #1 and I agree with your comments on the other options.

I just discovered a way to get the path of the addin without requiring the "Trust ..." setting:  Application.Workbooks("AddInFileName.xlam").Path.
Even if the Application.Workbooks.Count returns 0, it seems like the ThisWorkbook object of the addin is still there in the Workbooks collection, just hidden(?)!

This reduces the problem to only getting the file name of the active addin, and I think that this can be theoretically be done by using FindWindow to find the Excel VBE window, and thus its caption which includes the active (focused) addin file name. Same as Application.VBE.MainWindow.Caption, without requiring "Trust ...".
Then, we also need to spot the right one in case of multiple Excel applications but this could be done by comparing the window handle with Application.Hwnd, also without requiring "Trust ...".

What do you think about it?

**Comment by GCuser99** [comment]
@6DiegoDiego9, I'm glad you are giving some thought to this because the more I think about it, the less I like coercing user to set the "Trust ..." settings - a bug that you put in my ear!

Yes, your plan above sounds promising! Do you have time now to pursue, or should I?

**Comment by 6DiegoDiego9** [comment]
I think I'll give it a try in the next 1-2 days

**Comment by 6DiegoDiego9** [comment]
Done and tested successfully on my PC:

```
Option Explicit

Private Declare PtrSafe Function FindWindowEx Lib "user32" Alias "FindWindowExA" (ByVal hWnd1 As LongPtr, ByVal hWnd2 As LongPtr, ByVal lpsz1 As String, ByVal lpsz2 As String) As LongPtr
Declare PtrSafe Function GetWindowText Lib "user32" Alias "GetWindowTextA" (ByVal hWnd As LongPtr, ByVal lpString As String, ByVal cch As Long) As Long
Declare PtrSafe Function GetWindowTextLength Lib "user32" Alias "GetWindowTextLengthA" (ByVal hWnd As LongPtr) As Long
Private Declare PtrSafe Function GetWindowThreadProcessId Lib "user32" (ByVal hWnd As LongPtr, lpdwProcessId As Long) As Long

Public Function ActiveVBAProjectFolderFULLPath() As String
    'This returns the calling code project's parent document path. So if caller is from a project that references the SeleniumVBA Add-in
    'then this returns the path to the caller, not the Add-in (unless they are the same).
    'But be aware that if qc'ing this routine in Debug mode, the path to this SeleniumVBA project will be returned, which
    'may not be the caller's intended target if it resides in a different project.

    Dim GUID&(0 To 3): GUID(0) = &H20400: GUID(1) = &H0: GUID(2) = &HC0: GUID(3) = &H46000000
    
    Dim sRespType As String
    sRespType = TypeName(Application.Caller)
    If sRespType <> "Error" Then 'eg. if launched by a formula or button in a worksheet
        ActiveVBAProjectFolderFULLPath = ActiveWorkbook.FullName
    Else 'if launched in the VBE
        On Error Resume Next
        ActiveVBAProjectFolderFULLPath = Application.VBE.ActiveVBProject.Filename
        If Error <> 0 Then 'if Excel security setting "Trust access to the VBA project object model" is not enabled
            On Error GoTo 0
            Dim ThisAppProcessID As Long
            GetWindowThreadProcessId Application.hWnd, ThisAppProcessID
            Do 'search for this VBE window
                Dim hWnd As LongPtr
                hWnd = FindWindowEx(0, hWnd, "wndclass_desked_gsk", vbNullString)
                If hWnd > 0 Then
                    Dim WndProcessID As Long
                    GetWindowThreadProcessId hWnd, WndProcessID
                    If ThisAppProcessID = WndProcessID Then
                        'get its caption
                        Dim Length As Long, caption As String, result As Long
                        Length = GetWindowTextLength(hWnd)
                        caption = Space$(Length + 1)
                        result = GetWindowText(hWnd, caption, Length + 1)
                        
                        'extract filename from the caption
                        Dim oRegex As New regexp
                        oRegex.Pattern = "^Microsoft Visual Basic[^-]* - ([^[]*) \[[^]]+\] - \[[^(]+\([^)]+\)\]$"
                        Dim regexRes As MatchCollection
                        Set regexRes = oRegex.Execute(Left(caption, result))
                        If regexRes.Count = 1 Then
                            Dim sFilename As String
                            sFilename = regexRes.Item(0).SubMatches(0)
                            ActiveVBAProjectFolderFULLPath = Workbooks(sFilename).FullName
                        Else
                            Err.raise 1, , "Error: unable to extract filename from VBE window caption. Check the extraction regex."
                        End If
                    End If
                End If
            Loop Until hWnd = 0
        End If
    End If
    If ActiveVBAProjectFolderFULLPath = vbNullString Then Err.raise 1, , "Error: unable to get the active VBPrject path."
End Function

```
I opted to get the caller workbook path if called by a button (or formula) in a worksheet.  Do you agree?

Note2: I left fullpaths for testing. Convert fullpath to path after you successfully test it.

Ah please don't forget to send me your improved Enforce_Trust_Access_to_VBA_Project_Object_Model before throwing it away :)

**Comment by GCuser99** [comment]
@6DiegoDiego9 - this is awesome and appears in my testing to solve the problem perfectly!

A couple minor changes... For it to be a drop-in replacement for ActiveVBAProjectFolderPath, it needs to return the folder path (not file path), so I changed ".FullName" to ".Path" (is that what you meant in your Note2?) and employed FSO to get the parent folder path for the VBAIsTrusted branch. Also, there is the edge case where user has created a new workbook with calling vba module, but hasn't yet saved the workbook which will throw an error for the VBAIsTrusted branch. I made suggested modifications to handle that case and changed the final Err.Raise message to warn user to save the workbook if not saved.

PS: I certainly will NOT throw away your [clever fix to enforce trust to VBA project object model](https://github.com/GCuser99/SeleniumVBA/issues/68#issuecomment-1399294327) - I'm sure it will come in handy at some point in the future :-).

```vba
Public Function ActiveVBAProjectFolderFULLPath() As String
    'This returns the calling code project's parent document path. So if caller is from a project that references the SeleniumVBA Add-in
    'then this returns the path to the caller, not the Add-in (unless they are the same).
    'But be aware that if qc'ing this routine in Debug mode, the path to this SeleniumVBA project will be returned, which
    'may not be the caller's intended target if it resides in a different project.
    
    'need to either rename this or employ fso to get parent folder path
    Dim fso As New FileSystemObject
    Dim GUID&(0 To 3): GUID(0) = &H20400: GUID(1) = &H0: GUID(2) = &HC0: GUID(3) = &H46000000
    
    Dim sRespType As String
    sRespType = TypeName(Application.Caller)
    
    If sRespType <> "Error" Then 'eg. if launched by a formula or button in a worksheet
        ActiveVBAProjectFolderFULLPath = ActiveWorkbook.Path
    Else 'if launched in the VBE
        If VBAIsTrusted Then
            'below will return an error if active project's host doc has not yet been saved, even if access trusted
            On Error Resume Next
            ActiveVBAProjectFolderFULLPath = fso.GetParentFolderName(Application.VBE.ActiveVBProject.FileName)
            On Error GoTo 0
        Else 'if Excel security setting "Trust access to the VBA project object model" is not enabled
            Dim ThisAppProcessID As Long
            GetWindowThreadProcessId Application.hWnd, ThisAppProcessID
            Do 'search for this VBE window
                Dim hWnd As LongPtr
                hWnd = FindWindowEx(0, hWnd, "wndclass_desked_gsk", vbNullString)
                If hWnd > 0 Then
                    Dim WndProcessID As Long
                    GetWindowThreadProcessId hWnd, WndProcessID
                    If ThisAppProcessID = WndProcessID Then
                        'get its caption
                        Dim Length As Long, caption As String, result As Long
                        Length = GetWindowTextLength(hWnd)
                        caption = Space$(Length + 1)
                        result = GetWindowText(hWnd, caption, Length + 1)
                        
                        'extract filename from the caption
                        Dim oRegex As New regexp
                        oRegex.Pattern = "^Microsoft Visual Basic[^-]* - ([^[]*) \[[^]]+\] - \[[^(]+\([^)]+\)\]$"
                        Dim regexRes As MatchCollection
                        Set regexRes = oRegex.Execute(Left(caption, result))
                        If regexRes.Count = 1 Then
                            Dim sFilename As String
                            sFilename = regexRes.Item(0).SubMatches(0)
                            'this returns vbNullString if workbook has not been saved yet
                            ActiveVBAProjectFolderFULLPath = Workbooks(sFilename).Path
                        Else
                            Err.raise 1, , "Error: unable to extract filename from VBE window caption. Check the extraction regex."
                        End If
                    End If
                End If
            Loop Until hWnd = 0
        End If
    End If
    If ActiveVBAProjectFolderFULLPath = vbNullString Then Err.raise 1, , "Error: unable to get the active VBProject path - make sure the parent document has been saved."
End Function

Private Function VBAIsTrusted() As Boolean
    VBAIsTrusted = False
    On Error Resume Next
    VBAIsTrusted = (Application.VBE.VBProjects.Count) > 0
    On Error GoTo 0
End Function
```

**Comment by 6DiegoDiego9** [comment]
Perfect!

You correctly interpreted my Note2, just don't forget to also rename the function "ActiveVBAProjectFolderFULLPath" to "ActiveVBAProjectFolderPath" :)

Btw thanks for the link!

**Comment by 6DiegoDiego9** [comment]
Oh and I forgot to make the "Declare" all Private.

**Comment by GCuser99** [comment]
Good work on this @6DiegoDiego9. BTW, I had to make modifications in WebShared module to accommodate your Excel solution AND an Access solution. My previous solution worked fine for Access because it does not have a "Trust access..." option.  Strange...
