### ISSUE TITLE
ShadowRoot and xPath = KO

### ISSUE THREAD

**Issue by 6DiegoDiego9** [GCuser99/SeleniumVBA#77]
After hitting my head on my first case with ShadowRoot, where I can get an inner element by tagName and not by xPath, I came across some webpages explaining that xPath doesn't support finding elements inside ShadowRoots.

Can you confirm this?

If so, in the WebShadowRoot class, I'm inclined to create a dedicated private Enum By removing the "xPath" option.  Do you agree?

**Comment by GCuser99** [comment]
Thanks for catch this - the closest confirmation I have found is in the recent [release notes of Geckodriver](https://github.com/mozilla/geckodriver/releases) regarding ShadowRoot support:

"All location strategies except Tag name and XPath selector are currently supported."

Interestingly, I tested Tag Name selector on Chrome, Edge, and Firefox (version 113) and it seems to work fine. But I can confirm that XPath does not work on any of the browsers.

I'm ok with your idea of a dedicated Enum but won't it need to be declared public to be seen by a referencing external project?

I updated the Wiki docs to reflect your discovery.

Other ideas: 
Trap XPath selector use as a warning error to the user?
Add FindElement(s) convenience wrappers like we did for non-ShadowRoot FindElement(s) method but exclude XPath version?

Anyway, I'm good with any of these as long as the solution will work with an external referencing project.

Thanks again, Mike

**Comment by 6DiegoDiego9** [comment]
I kept the various options in mind for weeks, however, unable to reach a clear preference, I now opted for this minimal solution which is to only add an additional error description string if it already fails: https://github.com/GCuser99/SeleniumVBA/pull/81#issue-1717073333

Let's see how it goes :)

**Comment by GCuser99** [comment]
I like it!
