### ISSUE TITLE
Selenium.xlam blocked by Defender

### ISSUE THREAD

**Issue by 6DiegoDiego9** [GCuser99/SeleniumVBA#89]
Today my attempts to download Selenium.xlam or the whole repository in ZIP format get blocked by Defender:

![image](https://github.com/GCuser99/SeleniumVBA/assets/109476941/28dac591-acb7-4acd-93cc-d77375a94210)

Link: https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3AScript%2FWacatac.H!ml&threatid=2147814524

My version:

![image](https://github.com/GCuser99/SeleniumVBA/assets/109476941/68c9975e-3ed5-4873-96d2-57759f1d8e93)

Does it happen to you too?

**Comment by GCuser99** [comment]
yes - same happening to me. Scanning with  MalwareBytes results in no detection. Likely a false positive but I [submitted](https://www.microsoft.com/en-us/wdsi/filesubmission) SeleniumVBA.xlam file to Microsoft for further determination. Will let you know the results when I get them...

**Comment by GCuser99** [comment]
I have not received the Microsoft analysis back yet, but it looked like the file scanned negative by their cloud scanner, as part of the submission process.

I just updated Defender's security intelligence on my machine to v1.399.1471.0 and rescanned the xlam file in my GitHub desktop - no problems. I then tried downloading both the xlam and the release asset zip files from our GitHub repo and had no problem downloading. So presumably the false positive has been fixed in the latest version of Defender intelligence...? Can you update intelligence and try again? Thx.

**Comment by 6DiegoDiego9** [comment]
I just manually called an update of Windows Defender and now it passes for me too!
![image](https://github.com/GCuser99/SeleniumVBA/assets/109476941/b823a474-36a4-43e6-8a59-62f7f5e38ca8)
![image](https://github.com/GCuser99/SeleniumVBA/assets/109476941/6ec4915e-04bc-4986-abbd-bc76a5ea5231)


A pass on VirusTotal shows the keywords "download" and "heuristics"
![image](https://github.com/GCuser99/SeleniumVBA/assets/109476941/7853f6f8-5695-457b-9afa-8b507fa4ae55)

that makes me suspect that they may be (too much) sensible to our automatic download from the web (and execution) of the webdriver executable, without considering that we're just taking the official files from official Google/Microsoft/Mozilla servers:
![image](https://github.com/GCuser99/SeleniumVBA/assets/109476941/816e2dba-fa41-4da7-986a-79f009c61ecc)

I [saw](https://www.google.com/search?q=%22gvt1.com) that other security people had problems with the Google domain "gvt1.com" and antiviruses. Could this be it? we'll likely never know... :-)

**Comment by 6DiegoDiego9** [comment]
Closed (fixed by Microsoft)

**Comment by GCuser99** [comment]
MS submission report Analyst comments:

At this time, the submitted files do not meet our criteria for malware or potentially unwanted applications. The detection has been removed. Please follow the steps below to clear cached detections and obtain the latest malware definitions.
