### ISSUE TITLE
Virus in SeleniumVBA.xlam

### ISSUE THREAD

**Issue by jjsmeets** [GCuser99/SeleniumVBA#91]
trying to download DIST/seleniumvba.xlam on windows 11 detects a virus: Trojan:Script/Ulthar.A!ml

can not download the file.

I have added a (dutch) screenshot.

Detected by windows defender.
![virus mesage](https://github.com/GCuser99/SeleniumVBA/assets/16468439/515c728f-ca61-444c-8d9b-a22945531f45)

**Comment by 6DiegoDiego9** [comment]
See https://github.com/GCuser99/SeleniumVBA/issues/89#issuecomment-1783953229
(update Windows Defender)

Please let us know if the update doesn't fix it

**Comment by jjsmeets** [comment]
Not a duplicate because current window defender version 1.401.241.0 still detect virus.

**Comment by GCuser99** [comment]
@jjsmeets, I submitted the same exact file to MS Security Intelligence last week and it came back negative for a virus. Soon after making that submission, Defender stopped identifying the file has a trojan, and all was back to normal.

So I suspect the same is happening this time as well - a false positive. Out of an abundance of caution, I have resubmitted the file to MS Security Intelligence, and will let you know the outcome as soon as they get back to me....

Thanks for reporting,

Mike

**Comment by GCuser99** [comment]
@jjsmeets, I haven't yet got the result back from my submission to MS, but I just updated Defender to version 1.401.256.0 and can now download SeleniumVBA.xlam. Feels like a repeat from a week ago... Again, thanks for reporting and sorry for the inconvenience...

**Comment by jjsmeets** [comment]
today new version of windows defender present on my machine (1.401.271). This version does not detect a virus. So problem now solved.

**Comment by GCuser99** [comment]
Here is the submission results from Microsoft:
![image](https://github.com/GCuser99/SeleniumVBA/assets/26237126/2b393b2a-9aa1-428e-973c-2bb68c877d9c)
