### ISSUE TITLE
xlam-file issues

### ISSUE THREAD

**Issue by jjsmeets** [GCuser99/SeleniumVBA#92]
Because yesterday the xlam could not be downloaded I have downloaded the src and test directory. I also downloaded dev/tools and used the file update.xlms  to create the  xlam file myself.

Today I managed to download the xlam file because window defender does not detect a virus any more.

Now I have the following issues:
1
the self created xlam file uses the src modules and these module start with the following lines:
VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
End

My version of vba (using excel 2010 (= versie 14.0) does not recognize these statements. Can I comment them out
------------------------------------------------------------------------
2
The WebElement module contains:
Friend Property Set driver(objWebDriver As WebDriver)
    Set driver_ = objWebDriver
End Property

Friend Property Let elementId(ByVal val As String)
    elementId_ = val
End Property

Friend Property Get elementId() As String
    elementId = elementId_
End Property
These statements are also not recognized . Is removing the word friend ok?
--------------------------------------------------------------
3 also friends used in WebShadowRoot
--------------------------------------------------------------
4 all modules are imported as basic modules. Should the cls files not be class modules. I detected this because the classfactory module contains the statement specification 
Public Function New_WebDriver() As WebDriver 
this gives error message"module is not a type
So I expect that some went wrong in the update.xlsm creating the xlam file
------------------------------------------------------------
5 because the xlam file now could also be downloaded that file, However when opening the home generated xlam file is see the modules. When opening the downloaded xlam file I do not see anything in VBA-project explorer. So I cannot detect whether the home generated  xlam-file is really the same as the downloaded one.

**Comment by jjsmeets** [comment]
I found a hint what could be the the cause of the import problem as well as the 4 line headers. It seems (and I checked in in a hex editor that all files in the src directory in github end with \n (unix style and not \r\n (windows style).
According to the remarks and the solution on the website I found the github should change its configuration parameters.

See the following URL: 
https://github.com/VBA-tools/VBA-Web/issues/24

one of the last lines reads like:  _I've updated the git config to use Windows-style line endings for modules and classes and from what I can tell it fixes the issue.__

**Comment by GCuser99** [comment]
Hi @jjsmeets,

I'm surprised that after you successfully downloaded the xlam file, that you cannot see any modules. Can you double check that again? Here are some things to try:

1. After downloading the file, in File Explorer, click on the file, right-mouse-button Properties, and make sure at the bottom Security is set to "unblock" (Windows 11).
2. Now open the xlam file and make sure you click on Enable Macros on the MS Security popup if it shows.
3. In the VBA Project Explorer, you should see SeleniumVBA - do you see it? If so, click on it and that will expand to show the code modules.

While you double check that, I will work on the eol problem today.

Thanks, Mike

![image](https://github.com/GCuser99/SeleniumVBA/assets/26237126/bc7e65cd-d3b8-4918-bc44-4bfe1629add8)

**Comment by GCuser99** [comment]
@jjsmeets ,

I hope you had some luck finding the code modules for the SeleniumVBA.xlam file ([see my post above](https://github.com/GCuser99/SeleniumVBA/issues/92#issuecomment-1801980093)).

On your attempt to rebuild the xlam file from scratch... How did you download the *.bas and *.cls files? In order for the files to have the correct eol's for windows, you should download the source assets zip file from the [release section](https://github.com/GCuser99/SeleniumVBA/releases) of the GitHub repo:

![image](https://github.com/GCuser99/SeleniumVBA/assets/26237126/3cd5a786-95cc-4d3b-991f-6134a168dd36)

If you tried to download the RAW files from the src directory, then that is why you had an issue with end-of-lines, as the files are stored by default on GitHub with Unix-style end-of-lines for consistency.

Hopefully you will not have to rebuild the xlam file, but if you do attempt it, importing the source into Excel should not be a problem with the correct end-of-lines. Don't forget that you will have to set all of the [references](https://github.com/GCuser99/SeleniumVBA/blob/main/src/references.png)  in your rebuilt project.

Please let @6DiegoDiego9 and I know if you have any other questions or issues...

Mike

**Comment by jjsmeets** [comment]
Yes al is working now as I generated sources from the now save xlam file. (and regenerated an xlam from those sources.I did not find that release section so I downloaded the directory by copying the url (when i opened the src folder and the filled that url in the following web page (as I found I should do when downloading a folder somewhere explained on github).
That URL was: Download GitHub directory

| 
| 
|  | 
Download GitHub directory


 |

 |

 |


Sorry the mail editor does not show the url but a link, just klik on it and you will get to that url.
Groet John Smeets Docent: OO / UML/ RUP / Requirements en Test 

    Op woensdag 8 november 2023 om 21:29:02 CET schreef Mike ***@***.***>:  
 
 


@jssmeets,

I hope you had some luck finding the code modules for the SeleniumVBA.xlam file (see my post above).

On your attempt to rebuild the xlam file from scratch... How did you download the *.bas and *.cls files? In order for the files to have the correct eol's for windows, you should download the source assets zip file from the release section of the GitHub repo:



If you tried to download the RAW files from the src directory, then that is why you had an issue with end-of-lines, as the files are stored by default on GitHub with Unix-style end-of-lines for consistency.

Hopefully you will not have to rebuild the xlam file, but if you do attempt it, importing the source into Excel should not be a problem with the correct end-of-lines. Don't forget that you will have to set all of the references in your rebuilt project.

Please let @6DiegoDiego9 and I know if you have any other questions or issues...

Mike

**Comment by GCuser99** [comment]
Great, I'll close this for now...
