### ISSUE TITLE
Trojan:Script/Wacatac.B!ml

### ISSUE THREAD

**Issue by jovdamo86** [GCuser99/SeleniumVBA#93]
After downloading the test file "SeleniumVBA.xlam". It detected as Trojan by Windows Security.
![Issue](https://github.com/GCuser99/SeleniumVBA/assets/93892174/bb8a68b7-8f53-4902-a732-75b8db5a1012)

**Comment by 6DiegoDiego9** [comment]
Hi @jovdamo86, it happened some weeks ago and was fixed by Microsoft about one week later.
What's your version of Windows Security?

<img width="379" alt="image" src="https://github.com/GCuser99/SeleniumVBA/assets/109476941/2265ca65-47ba-4949-945a-7848b9377c00">

**Comment by GCuser99** [comment]
@jovdamo86, I just tried downloading with Defender 1.401.1710.0 with no detection.

**Comment by jovdamo86** [comment]
Strange if that's the case. will try to download it and try again.
By the way, I have version 1.401.1729.0

**Comment by GCuser99** [comment]
Ok, please let us know!

**Comment by GCuser99** [comment]
@jovdamo86, I'm closing this for now - let us know if you have any further issues...
